/**
 * OS2Kitos API - V1
 * <b><i>OBS: Dokumentation for V2 findes ved at skifte version på dokumentet til 2 øverst på siden</i></b><br/><br/><b>BEMÆRK: Ekstern Adgang TIL størstedelen af API V1 LUKKES. <a href=\'https://os2web.atlassian.net/wiki/spaces/KITOS/pages/657293331/API+Design+V1#Varsling-om-lukning\'>LÆS MERE HER</a>.</b><br/><br/><b>BEMÆRK: Lukningen påvirker ikke authorize endpointet</b><br/><br/>
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIDataRowDTO } from './dataRowDTO';


export interface APIItInterfaceDTO { 
    id?: number;
    uuid?: string;
    name?: string;
    url?: string;
    description?: string;
    note?: string;
    itInterfaceId?: string;
    organizationId?: number;
    organizationName?: string;
    objectOwnerName?: string;
    objectOwnerLastName?: string;
    readonly objectOwnerFullName?: string;
    accessModifier?: APIItInterfaceDTO.AccessModifierEnum;
    exhibitedById?: number;
    exhibitedByItSystemId?: number;
    exhibitedByItSystemName?: string;
    exhibitedByItSystemDisabled?: boolean;
    interfaceId?: number;
    interfaceName?: string;
    dataRows?: Array<APIDataRowDTO>;
    belongsToId?: number;
    belongsToName?: string;
    version?: string;
    /**
     * Gets or sets whether this instance has a usage in any organization.
     */
    isUsed?: boolean;
    disabled?: boolean;
    usedByOrganizationNames?: Array<string>;
}
export namespace APIItInterfaceDTO {
    export type AccessModifierEnum = 'Local' | 'Public';
    export const AccessModifierEnum = {
        Local: 'Local' as AccessModifierEnum,
        Public: 'Public' as AccessModifierEnum
    };
}


