/**
 * OS2Kitos API - V1
 * <b><i>OBS: Dokumentation for V2 findes ved at skifte version på dokumentet til 2 øverst på siden</i></b><br/><br/><b>BEMÆRK: Ekstern Adgang TIL størstedelen af API V1 LUKKES. <a href=\'https://os2web.atlassian.net/wiki/spaces/KITOS/pages/657293331/API+Design+V1#Varsling-om-lukning\'>LÆS MERE HER</a>.</b><br/><br/><b>BEMÆRK: Lukningen påvirker ikke authorize endpointet</b><br/><br/>
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIUserDTO } from './userDTO';


export interface APIOrganizationRightDTO { 
    organizationId?: number;
    organizationUuid?: string;
    organizationName?: string;
    role?: APIOrganizationRightDTO.RoleEnum;
    userId?: number;
    user?: APIUserDTO;
    userName?: string;
    userEmail?: string;
    lastChanged?: string;
    lastChangedByUserId?: number;
    objectOwnerName?: string;
    objectOwnerLastName?: string;
    readonly objectOwnerFullName?: string;
    defaultOrgUnitName?: string;
}
export namespace APIOrganizationRightDTO {
    export type RoleEnum = 'User' | 'LocalAdmin' | 'OrganizationModuleAdmin' | 'SystemModuleAdmin' | 'ContractModuleAdmin' | 'GlobalAdmin' | 'RightsHolderAccess';
    export const RoleEnum = {
        User: 'User' as RoleEnum,
        LocalAdmin: 'LocalAdmin' as RoleEnum,
        OrganizationModuleAdmin: 'OrganizationModuleAdmin' as RoleEnum,
        SystemModuleAdmin: 'SystemModuleAdmin' as RoleEnum,
        ContractModuleAdmin: 'ContractModuleAdmin' as RoleEnum,
        GlobalAdmin: 'GlobalAdmin' as RoleEnum,
        RightsHolderAccess: 'RightsHolderAccess' as RoleEnum
    };
}


