/**
 * KITOS API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIOrganizationRole = 'User' | 'LocalAdmin' | 'OrganizationModuleAdmin' | 'SystemModuleAdmin' | 'ContractModuleAdmin' | 'GlobalAdmin' | 'RightsHolderAccess';

export const APIOrganizationRole = {
    User: 'User' as APIOrganizationRole,
    LocalAdmin: 'LocalAdmin' as APIOrganizationRole,
    OrganizationModuleAdmin: 'OrganizationModuleAdmin' as APIOrganizationRole,
    SystemModuleAdmin: 'SystemModuleAdmin' as APIOrganizationRole,
    ContractModuleAdmin: 'ContractModuleAdmin' as APIOrganizationRole,
    GlobalAdmin: 'GlobalAdmin' as APIOrganizationRole,
    RightsHolderAccess: 'RightsHolderAccess' as APIOrganizationRole
};

