/**
 * KITOS API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIYesNoUndecidedOption } from './yesNoUndecidedOption';
import { APINamedEntityWithExpirationStatusDTO } from './namedEntityWithExpirationStatusDTO';


export interface APISubDataProcessorResponseDTO { 
    id?: number;
    name?: string | null;
    cvrNumber?: string | null;
    basisForTransfer?: APINamedEntityWithExpirationStatusDTO;
    transferToInsecureThirdCountries?: APIYesNoUndecidedOption;
    insecureCountry?: APINamedEntityWithExpirationStatusDTO;
}

