/**
 * OS2Kitos API - V1
 * <b><i>OBS: Dokumentation for V2 findes ved at skifte version på dokumentet til 2 øverst på siden</i></b><br/><br/><b>BEMÆRK: Ekstern Adgang TIL størstedelen af API V1 LUKKES. <a href=\'https://os2web.atlassian.net/wiki/spaces/KITOS/pages/657293331/API+Design+V1#Varsling-om-lukning\'>LÆS MERE HER</a>.</b><br/><br/><b>BEMÆRK: Lukningen påvirker ikke authorize endpointet</b><br/><br/>
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface APIYearMonthIntervalOptionNullableValueWithOptionalRemarkDTO { 
    value?: APIYearMonthIntervalOptionNullableValueWithOptionalRemarkDTO.ValueEnum;
    remark?: string;
}
export namespace APIYearMonthIntervalOptionNullableValueWithOptionalRemarkDTO {
    export type ValueEnum = 'Half_yearly' | 'Yearly' | 'Every_second_year' | 'Other' | 'Undecided';
    export const ValueEnum = {
        HalfYearly: 'Half_yearly' as ValueEnum,
        Yearly: 'Yearly' as ValueEnum,
        EverySecondYear: 'Every_second_year' as ValueEnum,
        Other: 'Other' as ValueEnum,
        Undecided: 'Undecided' as ValueEnum
    };
}


