export * from './authorize.service';
import { AuthorizeService } from './authorize.service';
export * from './dataProcessingRegistration.service';
import { DataProcessingRegistrationService } from './dataProcessingRegistration.service';
export * from './dataProcessingRegistrationReadModels.service';
import { DataProcessingRegistrationReadModelsService } from './dataProcessingRegistrationReadModels.service';
export * from './excelExport.service';
import { ExcelExportService } from './excelExport.service';
export * from './healthCheck.service';
import { HealthCheckService } from './healthCheck.service';
export * from './itContractOverviewReadModels.service';
import { ItContractOverviewReadModelsService } from './itContractOverviewReadModels.service';
export * from './itSystemUsageOptions.service';
import { ItSystemUsageOptionsService } from './itSystemUsageOptions.service';
export * from './itSystemUsageOverviewReadModels.service';
import { ItSystemUsageOverviewReadModelsService } from './itSystemUsageOverviewReadModels.service';
export * from './localAdminExcel.service';
import { LocalAdminExcelService } from './localAdminExcel.service';
export * from './metadata.service';
import { MetadataService } from './metadata.service';
export * from './sSO.service';
import { SSOService } from './sSO.service';
export * from './tokenAuthentication.service';
import { TokenAuthenticationService } from './tokenAuthentication.service';
export const APIS = [AuthorizeService, DataProcessingRegistrationService, DataProcessingRegistrationReadModelsService, ExcelExportService, HealthCheckService, ItContractOverviewReadModelsService, ItSystemUsageOptionsService, ItSystemUsageOverviewReadModelsService, LocalAdminExcelService, MetadataService, SSOService, TokenAuthenticationService];
