export * from './v1AdviceUserRelationINTERNAL.service';
import { APIV1AdviceUserRelationINTERNALService } from './v1AdviceUserRelationINTERNAL.service';
export * from './v1Authorize.service';
import { APIV1AuthorizeService } from './v1Authorize.service';
export * from './v1BrokenExternalReferencesReportINTERNAL.service';
import { APIV1BrokenExternalReferencesReportINTERNALService } from './v1BrokenExternalReferencesReportINTERNAL.service';
export * from './v1Contactperson.service';
import { APIV1ContactpersonService } from './v1Contactperson.service';
export * from './v1DataProcessingRegistration.service';
import { APIV1DataProcessingRegistrationService } from './v1DataProcessingRegistration.service';
export * from './v1DataProcessingRegistrationValidationINTERNAL.service';
import { APIV1DataProcessingRegistrationValidationINTERNALService } from './v1DataProcessingRegistrationValidationINTERNAL.service';
export * from './v1DataProtectionAdvisor.service';
import { APIV1DataProtectionAdvisorService } from './v1DataProtectionAdvisor.service';
export * from './v1DataResponsible.service';
import { APIV1DataResponsibleService } from './v1DataResponsible.service';
export * from './v1DataRow.service';
import { APIV1DataRowService } from './v1DataRow.service';
export * from './v1EconomyStream.service';
import { APIV1EconomyStreamService } from './v1EconomyStream.service';
export * from './v1ExcelINTERNAL.service';
import { APIV1ExcelINTERNALService } from './v1ExcelINTERNAL.service';
export * from './v1Exhibit.service';
import { APIV1ExhibitService } from './v1Exhibit.service';
export * from './v1GdprExportReportINTERNAL.service';
import { APIV1GdprExportReportINTERNALService } from './v1GdprExportReportINTERNAL.service';
export * from './v1GlobalAdminINTERNAL.service';
import { APIV1GlobalAdminINTERNALService } from './v1GlobalAdminINTERNAL.service';
export * from './v1HealthCheckINTERNAL.service';
import { APIV1HealthCheckINTERNALService } from './v1HealthCheckINTERNAL.service';
export * from './v1ItContract.service';
import { APIV1ItContractService } from './v1ItContract.service';
export * from './v1ItContractItSystemUsage.service';
import { APIV1ItContractItSystemUsageService } from './v1ItContractItSystemUsage.service';
export * from './v1ItContractRight.service';
import { APIV1ItContractRightService } from './v1ItContractRight.service';
export * from './v1ItInterface.service';
import { APIV1ItInterfaceService } from './v1ItInterface.service';
export * from './v1ItSystem.service';
import { APIV1ItSystemService } from './v1ItSystem.service';
export * from './v1ItSystemUsage.service';
import { APIV1ItSystemUsageService } from './v1ItSystemUsage.service';
export * from './v1ItSystemUsageDataSensitivityLevelINTERNAL.service';
import { APIV1ItSystemUsageDataSensitivityLevelINTERNALService } from './v1ItSystemUsageDataSensitivityLevelINTERNAL.service';
export * from './v1ItSystemUsageMigrationINTERNAL.service';
import { APIV1ItSystemUsageMigrationINTERNALService } from './v1ItSystemUsageMigrationINTERNAL.service';
export * from './v1ItSystemUsageOptionsINTERNAL.service';
import { APIV1ItSystemUsageOptionsINTERNALService } from './v1ItSystemUsageOptionsINTERNAL.service';
export * from './v1ItSystemUsageOrgUnitUsage.service';
import { APIV1ItSystemUsageOrgUnitUsageService } from './v1ItSystemUsageOrgUnitUsage.service';
export * from './v1ItSystemUsageRights.service';
import { APIV1ItSystemUsageRightsService } from './v1ItSystemUsageRights.service';
export * from './v1ItSystemUsageValidationINTERNAL.service';
import { APIV1ItSystemUsageValidationINTERNALService } from './v1ItSystemUsageValidationINTERNAL.service';
export * from './v1KLEINTERNAL.service';
import { APIV1KLEINTERNALService } from './v1KLEINTERNAL.service';
export * from './v1KendoOrganizationalConfigurationINTERNAL.service';
import { APIV1KendoOrganizationalConfigurationINTERNALService } from './v1KendoOrganizationalConfigurationINTERNAL.service';
export * from './v1ODATAAdviceINTERNAL.service';
import { APIV1ODATAAdviceINTERNALService } from './v1ODATAAdviceINTERNAL.service';
export * from './v1ODATAAdviceSentINTERNAL.service';
import { APIV1ODATAAdviceSentINTERNALService } from './v1ODATAAdviceSentINTERNAL.service';
export * from './v1ODATAAgreementElementTypesINTERNAL.service';
import { APIV1ODATAAgreementElementTypesINTERNALService } from './v1ODATAAgreementElementTypesINTERNAL.service';
export * from './v1ODATAArchiveLocationsINTERNAL.service';
import { APIV1ODATAArchiveLocationsINTERNALService } from './v1ODATAArchiveLocationsINTERNAL.service';
export * from './v1ODATAArchivePeriods.service';
import { APIV1ODATAArchivePeriodsService } from './v1ODATAArchivePeriods.service';
export * from './v1ODATAArchiveTestLocationsINTERNAL.service';
import { APIV1ODATAArchiveTestLocationsINTERNALService } from './v1ODATAArchiveTestLocationsINTERNAL.service';
export * from './v1ODATAArchiveTypesINTERNAL.service';
import { APIV1ODATAArchiveTypesINTERNALService } from './v1ODATAArchiveTypesINTERNAL.service';
export * from './v1ODATAAttachedOptions.service';
import { APIV1ODATAAttachedOptionsService } from './v1ODATAAttachedOptions.service';
export * from './v1ODATAAttachedOptionsRegisterTypesINTERNAL.service';
import { APIV1ODATAAttachedOptionsRegisterTypesINTERNALService } from './v1ODATAAttachedOptionsRegisterTypesINTERNAL.service';
export * from './v1ODATAAttachedOptionsSensitivePersonalDataINTERNAL.service';
import { APIV1ODATAAttachedOptionsSensitivePersonalDataINTERNALService } from './v1ODATAAttachedOptionsSensitivePersonalDataINTERNAL.service';
export * from './v1ODATABusinessTypesINTERNAL.service';
import { APIV1ODATABusinessTypesINTERNALService } from './v1ODATABusinessTypesINTERNAL.service';
export * from './v1ODATAConfigsINTERNAL.service';
import { APIV1ODATAConfigsINTERNALService } from './v1ODATAConfigsINTERNAL.service';
export * from './v1ODATACriticalityTypesINTERNAL.service';
import { APIV1ODATACriticalityTypesINTERNALService } from './v1ODATACriticalityTypesINTERNAL.service';
export * from './v1ODATADataProcessingBasisForTransferOptionsINTERNAL.service';
import { APIV1ODATADataProcessingBasisForTransferOptionsINTERNALService } from './v1ODATADataProcessingBasisForTransferOptionsINTERNAL.service';
export * from './v1ODATADataProcessingCountryOptionsINTERNAL.service';
import { APIV1ODATADataProcessingCountryOptionsINTERNALService } from './v1ODATADataProcessingCountryOptionsINTERNAL.service';
export * from './v1ODATADataProcessingDataResponsibleOptionsINTERNAL.service';
import { APIV1ODATADataProcessingDataResponsibleOptionsINTERNALService } from './v1ODATADataProcessingDataResponsibleOptionsINTERNAL.service';
export * from './v1ODATADataProcessingOversightOptionsINTERNAL.service';
import { APIV1ODATADataProcessingOversightOptionsINTERNALService } from './v1ODATADataProcessingOversightOptionsINTERNAL.service';
export * from './v1ODATADataProcessingRegistrationReadModelsINTERNAL.service';
import { APIV1ODATADataProcessingRegistrationReadModelsINTERNALService } from './v1ODATADataProcessingRegistrationReadModelsINTERNAL.service';
export * from './v1ODATADataProcessingRegistrationRights.service';
import { APIV1ODATADataProcessingRegistrationRightsService } from './v1ODATADataProcessingRegistrationRights.service';
export * from './v1ODATADataProcessingRegistrationRolesINTERNAL.service';
import { APIV1ODATADataProcessingRegistrationRolesINTERNALService } from './v1ODATADataProcessingRegistrationRolesINTERNAL.service';
export * from './v1ODATADataTypesINTERNAL.service';
import { APIV1ODATADataTypesINTERNALService } from './v1ODATADataTypesINTERNAL.service';
export * from './v1ODATAFrequencyTypesINTERNAL.service';
import { APIV1ODATAFrequencyTypesINTERNALService } from './v1ODATAFrequencyTypesINTERNAL.service';
export * from './v1ODATAHelpTextsINTERNAL.service';
import { APIV1ODATAHelpTextsINTERNALService } from './v1ODATAHelpTextsINTERNAL.service';
export * from './v1ODATAInterfaceTypesINTERNAL.service';
import { APIV1ODATAInterfaceTypesINTERNALService } from './v1ODATAInterfaceTypesINTERNAL.service';
export * from './v1ODATAItContractAgreementElementTypes.service';
import { APIV1ODATAItContractAgreementElementTypesService } from './v1ODATAItContractAgreementElementTypes.service';
export * from './v1ODATAItContractItSystemUsages.service';
import { APIV1ODATAItContractItSystemUsagesService } from './v1ODATAItContractItSystemUsages.service';
export * from './v1ODATAItContractOverviewReadModelsINTERNAL.service';
import { APIV1ODATAItContractOverviewReadModelsINTERNALService } from './v1ODATAItContractOverviewReadModelsINTERNAL.service';
export * from './v1ODATAItContractRights.service';
import { APIV1ODATAItContractRightsService } from './v1ODATAItContractRights.service';
export * from './v1ODATAItContractRolesINTERNAL.service';
import { APIV1ODATAItContractRolesINTERNALService } from './v1ODATAItContractRolesINTERNAL.service';
export * from './v1ODATAItContractTemplateTypesINTERNAL.service';
import { APIV1ODATAItContractTemplateTypesINTERNALService } from './v1ODATAItContractTemplateTypesINTERNAL.service';
export * from './v1ODATAItContractTypesINTERNAL.service';
import { APIV1ODATAItContractTypesINTERNALService } from './v1ODATAItContractTypesINTERNAL.service';
export * from './v1ODATAItContracts.service';
import { APIV1ODATAItContractsService } from './v1ODATAItContracts.service';
export * from './v1ODATAItInterfaceExhibits.service';
import { APIV1ODATAItInterfaceExhibitsService } from './v1ODATAItInterfaceExhibits.service';
export * from './v1ODATAItInterfaces.service';
import { APIV1ODATAItInterfacesService } from './v1ODATAItInterfaces.service';
export * from './v1ODATAItSystemCategoriesINTERNAL.service';
import { APIV1ODATAItSystemCategoriesINTERNALService } from './v1ODATAItSystemCategoriesINTERNAL.service';
export * from './v1ODATAItSystemRights.service';
import { APIV1ODATAItSystemRightsService } from './v1ODATAItSystemRights.service';
export * from './v1ODATAItSystemRolesINTERNAL.service';
import { APIV1ODATAItSystemRolesINTERNALService } from './v1ODATAItSystemRolesINTERNAL.service';
export * from './v1ODATAItSystemUsageOverviewReadModelsINTERNAL.service';
import { APIV1ODATAItSystemUsageOverviewReadModelsINTERNALService } from './v1ODATAItSystemUsageOverviewReadModelsINTERNAL.service';
export * from './v1ODATAItSystemUsages.service';
import { APIV1ODATAItSystemUsagesService } from './v1ODATAItSystemUsages.service';
export * from './v1ODATAItSystems.service';
import { APIV1ODATAItSystemsService } from './v1ODATAItSystems.service';
export * from './v1ODATALocalAgreementElementTypesINTERNAL.service';
import { APIV1ODATALocalAgreementElementTypesINTERNALService } from './v1ODATALocalAgreementElementTypesINTERNAL.service';
export * from './v1ODATALocalArchiveLocationsINTERNAL.service';
import { APIV1ODATALocalArchiveLocationsINTERNALService } from './v1ODATALocalArchiveLocationsINTERNAL.service';
export * from './v1ODATALocalArchiveTestLocationsINTERNAL.service';
import { APIV1ODATALocalArchiveTestLocationsINTERNALService } from './v1ODATALocalArchiveTestLocationsINTERNAL.service';
export * from './v1ODATALocalArchiveTypesINTERNAL.service';
import { APIV1ODATALocalArchiveTypesINTERNALService } from './v1ODATALocalArchiveTypesINTERNAL.service';
export * from './v1ODATALocalBusinessTypesINTERNAL.service';
import { APIV1ODATALocalBusinessTypesINTERNALService } from './v1ODATALocalBusinessTypesINTERNAL.service';
export * from './v1ODATALocalCriticalityTypesINTERNAL.service';
import { APIV1ODATALocalCriticalityTypesINTERNALService } from './v1ODATALocalCriticalityTypesINTERNAL.service';
export * from './v1ODATALocalDataProcessingBasisForTransferOptions.service';
import { APIV1ODATALocalDataProcessingBasisForTransferOptionsService } from './v1ODATALocalDataProcessingBasisForTransferOptions.service';
export * from './v1ODATALocalDataProcessingCountryOptions.service';
import { APIV1ODATALocalDataProcessingCountryOptionsService } from './v1ODATALocalDataProcessingCountryOptions.service';
export * from './v1ODATALocalDataProcessingDataResponsibleOptions.service';
import { APIV1ODATALocalDataProcessingDataResponsibleOptionsService } from './v1ODATALocalDataProcessingDataResponsibleOptions.service';
export * from './v1ODATALocalDataProcessingOversightOptions.service';
import { APIV1ODATALocalDataProcessingOversightOptionsService } from './v1ODATALocalDataProcessingOversightOptions.service';
export * from './v1ODATALocalDataProcessingRegistrationRoles.service';
import { APIV1ODATALocalDataProcessingRegistrationRolesService } from './v1ODATALocalDataProcessingRegistrationRoles.service';
export * from './v1ODATALocalDataTypesINTERNAL.service';
import { APIV1ODATALocalDataTypesINTERNALService } from './v1ODATALocalDataTypesINTERNAL.service';
export * from './v1ODATALocalFrequencyTypesINTERNAL.service';
import { APIV1ODATALocalFrequencyTypesINTERNALService } from './v1ODATALocalFrequencyTypesINTERNAL.service';
export * from './v1ODATALocalInterfaceTypesINTERNAL.service';
import { APIV1ODATALocalInterfaceTypesINTERNALService } from './v1ODATALocalInterfaceTypesINTERNAL.service';
export * from './v1ODATALocalItContractRolesINTERNAL.service';
import { APIV1ODATALocalItContractRolesINTERNALService } from './v1ODATALocalItContractRolesINTERNAL.service';
export * from './v1ODATALocalItContractTemplateTypesINTERNAL.service';
import { APIV1ODATALocalItContractTemplateTypesINTERNALService } from './v1ODATALocalItContractTemplateTypesINTERNAL.service';
export * from './v1ODATALocalItContractTypesINTERNAL.service';
import { APIV1ODATALocalItContractTypesINTERNALService } from './v1ODATALocalItContractTypesINTERNAL.service';
export * from './v1ODATALocalItSystemCategoriesINTERNAL.service';
import { APIV1ODATALocalItSystemCategoriesINTERNALService } from './v1ODATALocalItSystemCategoriesINTERNAL.service';
export * from './v1ODATALocalItSystemRoles.service';
import { APIV1ODATALocalItSystemRolesService } from './v1ODATALocalItSystemRoles.service';
export * from './v1ODATALocalOptionExtendTypesINTERNAL.service';
import { APIV1ODATALocalOptionExtendTypesINTERNALService } from './v1ODATALocalOptionExtendTypesINTERNAL.service';
export * from './v1ODATALocalOrganizationUnitRolesINTERNAL.service';
import { APIV1ODATALocalOrganizationUnitRolesINTERNALService } from './v1ODATALocalOrganizationUnitRolesINTERNAL.service';
export * from './v1ODATALocalPaymentFrequencyTypesINTERNAL.service';
import { APIV1ODATALocalPaymentFrequencyTypesINTERNALService } from './v1ODATALocalPaymentFrequencyTypesINTERNAL.service';
export * from './v1ODATALocalPaymentModelTypesINTERNAL.service';
import { APIV1ODATALocalPaymentModelTypesINTERNALService } from './v1ODATALocalPaymentModelTypesINTERNAL.service';
export * from './v1ODATALocalPriceRegulationTypesINTERNAL.service';
import { APIV1ODATALocalPriceRegulationTypesINTERNALService } from './v1ODATALocalPriceRegulationTypesINTERNAL.service';
export * from './v1ODATALocalProcurementStrategyTypesINTERNAL.service';
import { APIV1ODATALocalProcurementStrategyTypesINTERNALService } from './v1ODATALocalProcurementStrategyTypesINTERNAL.service';
export * from './v1ODATALocalPurchaseFormTypesINTERNAL.service';
import { APIV1ODATALocalPurchaseFormTypesINTERNALService } from './v1ODATALocalPurchaseFormTypesINTERNAL.service';
export * from './v1ODATALocalRegisterTypesINTERNAL.service';
import { APIV1ODATALocalRegisterTypesINTERNALService } from './v1ODATALocalRegisterTypesINTERNAL.service';
export * from './v1ODATALocalSensitiveDataTypesINTERNAL.service';
import { APIV1ODATALocalSensitiveDataTypesINTERNALService } from './v1ODATALocalSensitiveDataTypesINTERNAL.service';
export * from './v1ODATALocalSensitivePersonalDataTypesINTERNAL.service';
import { APIV1ODATALocalSensitivePersonalDataTypesINTERNALService } from './v1ODATALocalSensitivePersonalDataTypesINTERNAL.service';
export * from './v1ODATALocalTerminationDeadlineTypesINTERNAL.service';
import { APIV1ODATALocalTerminationDeadlineTypesINTERNALService } from './v1ODATALocalTerminationDeadlineTypesINTERNAL.service';
export * from './v1ODATAOptionExtendTypesINTERNAL.service';
import { APIV1ODATAOptionExtendTypesINTERNALService } from './v1ODATAOptionExtendTypesINTERNAL.service';
export * from './v1ODATAOrganizationRightsINTERNAL.service';
import { APIV1ODATAOrganizationRightsINTERNALService } from './v1ODATAOrganizationRightsINTERNAL.service';
export * from './v1ODATAOrganizationUnitRightsINTERNAL.service';
import { APIV1ODATAOrganizationUnitRightsINTERNALService } from './v1ODATAOrganizationUnitRightsINTERNAL.service';
export * from './v1ODATAOrganizationUnitRolesINTERNAL.service';
import { APIV1ODATAOrganizationUnitRolesINTERNALService } from './v1ODATAOrganizationUnitRolesINTERNAL.service';
export * from './v1ODATAOrganizationUnitsINTERNAL.service';
import { APIV1ODATAOrganizationUnitsINTERNALService } from './v1ODATAOrganizationUnitsINTERNAL.service';
export * from './v1ODATAOrganizationsINTERNAL.service';
import { APIV1ODATAOrganizationsINTERNALService } from './v1ODATAOrganizationsINTERNAL.service';
export * from './v1ODATAPaymentFrequencyTypesINTERNAL.service';
import { APIV1ODATAPaymentFrequencyTypesINTERNALService } from './v1ODATAPaymentFrequencyTypesINTERNAL.service';
export * from './v1ODATAPaymentModelTypesINTERNAL.service';
import { APIV1ODATAPaymentModelTypesINTERNALService } from './v1ODATAPaymentModelTypesINTERNAL.service';
export * from './v1ODATAPriceRegulationTypesINTERNAL.service';
import { APIV1ODATAPriceRegulationTypesINTERNALService } from './v1ODATAPriceRegulationTypesINTERNAL.service';
export * from './v1ODATAProcurementStrategyTypesINTERNAL.service';
import { APIV1ODATAProcurementStrategyTypesINTERNALService } from './v1ODATAProcurementStrategyTypesINTERNAL.service';
export * from './v1ODATAPurchaseFormTypesINTERNAL.service';
import { APIV1ODATAPurchaseFormTypesINTERNALService } from './v1ODATAPurchaseFormTypesINTERNAL.service';
export * from './v1ODATARegisterTypesINTERNAL.service';
import { APIV1ODATARegisterTypesINTERNALService } from './v1ODATARegisterTypesINTERNAL.service';
export * from './v1ODATASSO.service';
import { APIV1ODATASSOService } from './v1ODATASSO.service';
export * from './v1ODATASensitiveDataTypesINTERNAL.service';
import { APIV1ODATASensitiveDataTypesINTERNALService } from './v1ODATASensitiveDataTypesINTERNAL.service';
export * from './v1ODATASensitivePersonalDataTypesINTERNAL.service';
import { APIV1ODATASensitivePersonalDataTypesINTERNALService } from './v1ODATASensitivePersonalDataTypesINTERNAL.service';
export * from './v1ODATATerminationDeadlineTypesINTERNAL.service';
import { APIV1ODATATerminationDeadlineTypesINTERNALService } from './v1ODATATerminationDeadlineTypesINTERNAL.service';
export * from './v1ODATAUsersINTERNAL.service';
import { APIV1ODATAUsersINTERNALService } from './v1ODATAUsersINTERNAL.service';
export * from './v1OrganizationINTERNAL.service';
import { APIV1OrganizationINTERNALService } from './v1OrganizationINTERNAL.service';
export * from './v1OrganizationLifeCycleINTERNAL.service';
import { APIV1OrganizationLifeCycleINTERNALService } from './v1OrganizationLifeCycleINTERNAL.service';
export * from './v1OrganizationPermissionsINTERNAL.service';
import { APIV1OrganizationPermissionsINTERNALService } from './v1OrganizationPermissionsINTERNAL.service';
export * from './v1OrganizationRightINTERNAL.service';
import { APIV1OrganizationRightINTERNALService } from './v1OrganizationRightINTERNAL.service';
export * from './v1OrganizationUnitINTERNAL.service';
import { APIV1OrganizationUnitINTERNALService } from './v1OrganizationUnitINTERNAL.service';
export * from './v1OrganizationUnitLifeCycleINTERNAL.service';
import { APIV1OrganizationUnitLifeCycleINTERNALService } from './v1OrganizationUnitLifeCycleINTERNAL.service';
export * from './v1OrganizationUnitPermissionsINTERNAL.service';
import { APIV1OrganizationUnitPermissionsINTERNALService } from './v1OrganizationUnitPermissionsINTERNAL.service';
export * from './v1OrganizationUnitRegistrationINTERNAL.service';
import { APIV1OrganizationUnitRegistrationINTERNALService } from './v1OrganizationUnitRegistrationINTERNAL.service';
export * from './v1OrganizationUnitRightINTERNAL.service';
import { APIV1OrganizationUnitRightINTERNALService } from './v1OrganizationUnitRightINTERNAL.service';
export * from './v1PasswordResetRequest.service';
import { APIV1PasswordResetRequestService } from './v1PasswordResetRequest.service';
export * from './v1Reference.service';
import { APIV1ReferenceService } from './v1Reference.service';
export * from './v1StsOrganizationSynchronizationINTERNAL.service';
import { APIV1StsOrganizationSynchronizationINTERNALService } from './v1StsOrganizationSynchronizationINTERNAL.service';
export * from './v1SystemRelation.service';
import { APIV1SystemRelationService } from './v1SystemRelation.service';
export * from './v1TaskRef.service';
import { APIV1TaskRefService } from './v1TaskRef.service';
export * from './v1TextINTERNAL.service';
import { APIV1TextINTERNALService } from './v1TextINTERNAL.service';
export * from './v1UIModuleCustomizationINTERNAL.service';
import { APIV1UIModuleCustomizationINTERNALService } from './v1UIModuleCustomizationINTERNAL.service';
export * from './v1UserAdministrationPermissions.service';
import { APIV1UserAdministrationPermissionsService } from './v1UserAdministrationPermissions.service';
export * from './v1UserDeletion.service';
import { APIV1UserDeletionService } from './v1UserDeletion.service';
export * from './v1UserINTERNAL.service';
import { APIV1UserINTERNALService } from './v1UserINTERNAL.service';
export * from './v1UserNotificationINTERNAL.service';
import { APIV1UserNotificationINTERNALService } from './v1UserNotificationINTERNAL.service';
export * from './v1UserRolesManagementINTERNAL.service';
import { APIV1UserRolesManagementINTERNALService } from './v1UserRolesManagementINTERNAL.service';
export const APIS = [APIV1AdviceUserRelationINTERNALService, APIV1AuthorizeService, APIV1BrokenExternalReferencesReportINTERNALService, APIV1ContactpersonService, APIV1DataProcessingRegistrationService, APIV1DataProcessingRegistrationValidationINTERNALService, APIV1DataProtectionAdvisorService, APIV1DataResponsibleService, APIV1DataRowService, APIV1EconomyStreamService, APIV1ExcelINTERNALService, APIV1ExhibitService, APIV1GdprExportReportINTERNALService, APIV1GlobalAdminINTERNALService, APIV1HealthCheckINTERNALService, APIV1ItContractService, APIV1ItContractItSystemUsageService, APIV1ItContractRightService, APIV1ItInterfaceService, APIV1ItSystemService, APIV1ItSystemUsageService, APIV1ItSystemUsageDataSensitivityLevelINTERNALService, APIV1ItSystemUsageMigrationINTERNALService, APIV1ItSystemUsageOptionsINTERNALService, APIV1ItSystemUsageOrgUnitUsageService, APIV1ItSystemUsageRightsService, APIV1ItSystemUsageValidationINTERNALService, APIV1KLEINTERNALService, APIV1KendoOrganizationalConfigurationINTERNALService, APIV1ODATAAdviceINTERNALService, APIV1ODATAAdviceSentINTERNALService, APIV1ODATAAgreementElementTypesINTERNALService, APIV1ODATAArchiveLocationsINTERNALService, APIV1ODATAArchivePeriodsService, APIV1ODATAArchiveTestLocationsINTERNALService, APIV1ODATAArchiveTypesINTERNALService, APIV1ODATAAttachedOptionsService, APIV1ODATAAttachedOptionsRegisterTypesINTERNALService, APIV1ODATAAttachedOptionsSensitivePersonalDataINTERNALService, APIV1ODATABusinessTypesINTERNALService, APIV1ODATAConfigsINTERNALService, APIV1ODATACriticalityTypesINTERNALService, APIV1ODATADataProcessingBasisForTransferOptionsINTERNALService, APIV1ODATADataProcessingCountryOptionsINTERNALService, APIV1ODATADataProcessingDataResponsibleOptionsINTERNALService, APIV1ODATADataProcessingOversightOptionsINTERNALService, APIV1ODATADataProcessingRegistrationReadModelsINTERNALService, APIV1ODATADataProcessingRegistrationRightsService, APIV1ODATADataProcessingRegistrationRolesINTERNALService, APIV1ODATADataTypesINTERNALService, APIV1ODATAFrequencyTypesINTERNALService, APIV1ODATAHelpTextsINTERNALService, APIV1ODATAInterfaceTypesINTERNALService, APIV1ODATAItContractAgreementElementTypesService, APIV1ODATAItContractItSystemUsagesService, APIV1ODATAItContractOverviewReadModelsINTERNALService, APIV1ODATAItContractRightsService, APIV1ODATAItContractRolesINTERNALService, APIV1ODATAItContractTemplateTypesINTERNALService, APIV1ODATAItContractTypesINTERNALService, APIV1ODATAItContractsService, APIV1ODATAItInterfaceExhibitsService, APIV1ODATAItInterfacesService, APIV1ODATAItSystemCategoriesINTERNALService, APIV1ODATAItSystemRightsService, APIV1ODATAItSystemRolesINTERNALService, APIV1ODATAItSystemUsageOverviewReadModelsINTERNALService, APIV1ODATAItSystemUsagesService, APIV1ODATAItSystemsService, APIV1ODATALocalAgreementElementTypesINTERNALService, APIV1ODATALocalArchiveLocationsINTERNALService, APIV1ODATALocalArchiveTestLocationsINTERNALService, APIV1ODATALocalArchiveTypesINTERNALService, APIV1ODATALocalBusinessTypesINTERNALService, APIV1ODATALocalCriticalityTypesINTERNALService, APIV1ODATALocalDataProcessingBasisForTransferOptionsService, APIV1ODATALocalDataProcessingCountryOptionsService, APIV1ODATALocalDataProcessingDataResponsibleOptionsService, APIV1ODATALocalDataProcessingOversightOptionsService, APIV1ODATALocalDataProcessingRegistrationRolesService, APIV1ODATALocalDataTypesINTERNALService, APIV1ODATALocalFrequencyTypesINTERNALService, APIV1ODATALocalInterfaceTypesINTERNALService, APIV1ODATALocalItContractRolesINTERNALService, APIV1ODATALocalItContractTemplateTypesINTERNALService, APIV1ODATALocalItContractTypesINTERNALService, APIV1ODATALocalItSystemCategoriesINTERNALService, APIV1ODATALocalItSystemRolesService, APIV1ODATALocalOptionExtendTypesINTERNALService, APIV1ODATALocalOrganizationUnitRolesINTERNALService, APIV1ODATALocalPaymentFrequencyTypesINTERNALService, APIV1ODATALocalPaymentModelTypesINTERNALService, APIV1ODATALocalPriceRegulationTypesINTERNALService, APIV1ODATALocalProcurementStrategyTypesINTERNALService, APIV1ODATALocalPurchaseFormTypesINTERNALService, APIV1ODATALocalRegisterTypesINTERNALService, APIV1ODATALocalSensitiveDataTypesINTERNALService, APIV1ODATALocalSensitivePersonalDataTypesINTERNALService, APIV1ODATALocalTerminationDeadlineTypesINTERNALService, APIV1ODATAOptionExtendTypesINTERNALService, APIV1ODATAOrganizationRightsINTERNALService, APIV1ODATAOrganizationUnitRightsINTERNALService, APIV1ODATAOrganizationUnitRolesINTERNALService, APIV1ODATAOrganizationUnitsINTERNALService, APIV1ODATAOrganizationsINTERNALService, APIV1ODATAPaymentFrequencyTypesINTERNALService, APIV1ODATAPaymentModelTypesINTERNALService, APIV1ODATAPriceRegulationTypesINTERNALService, APIV1ODATAProcurementStrategyTypesINTERNALService, APIV1ODATAPurchaseFormTypesINTERNALService, APIV1ODATARegisterTypesINTERNALService, APIV1ODATASSOService, APIV1ODATASensitiveDataTypesINTERNALService, APIV1ODATASensitivePersonalDataTypesINTERNALService, APIV1ODATATerminationDeadlineTypesINTERNALService, APIV1ODATAUsersINTERNALService, APIV1OrganizationINTERNALService, APIV1OrganizationLifeCycleINTERNALService, APIV1OrganizationPermissionsINTERNALService, APIV1OrganizationRightINTERNALService, APIV1OrganizationUnitINTERNALService, APIV1OrganizationUnitLifeCycleINTERNALService, APIV1OrganizationUnitPermissionsINTERNALService, APIV1OrganizationUnitRegistrationINTERNALService, APIV1OrganizationUnitRightINTERNALService, APIV1PasswordResetRequestService, APIV1ReferenceService, APIV1StsOrganizationSynchronizationINTERNALService, APIV1SystemRelationService, APIV1TaskRefService, APIV1TextINTERNALService, APIV1UIModuleCustomizationINTERNALService, APIV1UserAdministrationPermissionsService, APIV1UserDeletionService, APIV1UserINTERNALService, APIV1UserNotificationINTERNALService, APIV1UserRolesManagementINTERNALService];
