export * from './aPIV1Authorize.service';
import { APIV1AuthorizeService } from './aPIV1Authorize.service';
export * from './aPIV1Authorize.serviceInterface';
export * from './aPIV1Contactperson.service';
import { APIV1ContactpersonService } from './aPIV1Contactperson.service';
export * from './aPIV1Contactperson.serviceInterface';
export * from './aPIV1DataProcessingRegistration.service';
import { APIV1DataProcessingRegistrationService } from './aPIV1DataProcessingRegistration.service';
export * from './aPIV1DataProcessingRegistration.serviceInterface';
export * from './aPIV1DataProtectionAdvisor.service';
import { APIV1DataProtectionAdvisorService } from './aPIV1DataProtectionAdvisor.service';
export * from './aPIV1DataProtectionAdvisor.serviceInterface';
export * from './aPIV1DataResponsible.service';
import { APIV1DataResponsibleService } from './aPIV1DataResponsible.service';
export * from './aPIV1DataResponsible.serviceInterface';
export * from './aPIV1DataRow.service';
import { APIV1DataRowService } from './aPIV1DataRow.service';
export * from './aPIV1DataRow.serviceInterface';
export * from './aPIV1EconomyStream.service';
import { APIV1EconomyStreamService } from './aPIV1EconomyStream.service';
export * from './aPIV1EconomyStream.serviceInterface';
export * from './aPIV1Exhibit.service';
import { APIV1ExhibitService } from './aPIV1Exhibit.service';
export * from './aPIV1Exhibit.serviceInterface';
export * from './aPIV1ItContract.service';
import { APIV1ItContractService } from './aPIV1ItContract.service';
export * from './aPIV1ItContract.serviceInterface';
export * from './aPIV1ItContractItSystemUsage.service';
import { APIV1ItContractItSystemUsageService } from './aPIV1ItContractItSystemUsage.service';
export * from './aPIV1ItContractItSystemUsage.serviceInterface';
export * from './aPIV1ItContractRight.service';
import { APIV1ItContractRightService } from './aPIV1ItContractRight.service';
export * from './aPIV1ItContractRight.serviceInterface';
export * from './aPIV1ItInterface.service';
import { APIV1ItInterfaceService } from './aPIV1ItInterface.service';
export * from './aPIV1ItInterface.serviceInterface';
export * from './aPIV1ItSystem.service';
import { APIV1ItSystemService } from './aPIV1ItSystem.service';
export * from './aPIV1ItSystem.serviceInterface';
export * from './aPIV1ItSystemUsage.service';
import { APIV1ItSystemUsageService } from './aPIV1ItSystemUsage.service';
export * from './aPIV1ItSystemUsage.serviceInterface';
export * from './aPIV1ItSystemUsageOrgUnitUsage.service';
import { APIV1ItSystemUsageOrgUnitUsageService } from './aPIV1ItSystemUsageOrgUnitUsage.service';
export * from './aPIV1ItSystemUsageOrgUnitUsage.serviceInterface';
export * from './aPIV1ItSystemUsageRights.service';
import { APIV1ItSystemUsageRightsService } from './aPIV1ItSystemUsageRights.service';
export * from './aPIV1ItSystemUsageRights.serviceInterface';
export * from './aPIV1ODATAArchivePeriods.service';
import { APIV1ODATAArchivePeriodsService } from './aPIV1ODATAArchivePeriods.service';
export * from './aPIV1ODATAArchivePeriods.serviceInterface';
export * from './aPIV1ODATAAttachedOptions.service';
import { APIV1ODATAAttachedOptionsService } from './aPIV1ODATAAttachedOptions.service';
export * from './aPIV1ODATAAttachedOptions.serviceInterface';
export * from './aPIV1ODATADataProcessingRegistrationRights.service';
import { APIV1ODATADataProcessingRegistrationRightsService } from './aPIV1ODATADataProcessingRegistrationRights.service';
export * from './aPIV1ODATADataProcessingRegistrationRights.serviceInterface';
export * from './aPIV1ODATAItContractAgreementElementTypes.service';
import { APIV1ODATAItContractAgreementElementTypesService } from './aPIV1ODATAItContractAgreementElementTypes.service';
export * from './aPIV1ODATAItContractAgreementElementTypes.serviceInterface';
export * from './aPIV1ODATAItContractItSystemUsages.service';
import { APIV1ODATAItContractItSystemUsagesService } from './aPIV1ODATAItContractItSystemUsages.service';
export * from './aPIV1ODATAItContractItSystemUsages.serviceInterface';
export * from './aPIV1ODATAItContractRights.service';
import { APIV1ODATAItContractRightsService } from './aPIV1ODATAItContractRights.service';
export * from './aPIV1ODATAItContractRights.serviceInterface';
export * from './aPIV1ODATAItContracts.service';
import { APIV1ODATAItContractsService } from './aPIV1ODATAItContracts.service';
export * from './aPIV1ODATAItContracts.serviceInterface';
export * from './aPIV1ODATAItInterfaceExhibits.service';
import { APIV1ODATAItInterfaceExhibitsService } from './aPIV1ODATAItInterfaceExhibits.service';
export * from './aPIV1ODATAItInterfaceExhibits.serviceInterface';
export * from './aPIV1ODATAItInterfaces.service';
import { APIV1ODATAItInterfacesService } from './aPIV1ODATAItInterfaces.service';
export * from './aPIV1ODATAItInterfaces.serviceInterface';
export * from './aPIV1ODATAItSystemRights.service';
import { APIV1ODATAItSystemRightsService } from './aPIV1ODATAItSystemRights.service';
export * from './aPIV1ODATAItSystemRights.serviceInterface';
export * from './aPIV1ODATAItSystemUsages.service';
import { APIV1ODATAItSystemUsagesService } from './aPIV1ODATAItSystemUsages.service';
export * from './aPIV1ODATAItSystemUsages.serviceInterface';
export * from './aPIV1ODATAItSystems.service';
import { APIV1ODATAItSystemsService } from './aPIV1ODATAItSystems.service';
export * from './aPIV1ODATAItSystems.serviceInterface';
export * from './aPIV1ODATALocalDataProcessingBasisForTransferOptions.service';
import { APIV1ODATALocalDataProcessingBasisForTransferOptionsService } from './aPIV1ODATALocalDataProcessingBasisForTransferOptions.service';
export * from './aPIV1ODATALocalDataProcessingBasisForTransferOptions.serviceInterface';
export * from './aPIV1ODATALocalDataProcessingCountryOptions.service';
import { APIV1ODATALocalDataProcessingCountryOptionsService } from './aPIV1ODATALocalDataProcessingCountryOptions.service';
export * from './aPIV1ODATALocalDataProcessingCountryOptions.serviceInterface';
export * from './aPIV1ODATALocalDataProcessingDataResponsibleOptions.service';
import { APIV1ODATALocalDataProcessingDataResponsibleOptionsService } from './aPIV1ODATALocalDataProcessingDataResponsibleOptions.service';
export * from './aPIV1ODATALocalDataProcessingDataResponsibleOptions.serviceInterface';
export * from './aPIV1ODATALocalDataProcessingOversightOptions.service';
import { APIV1ODATALocalDataProcessingOversightOptionsService } from './aPIV1ODATALocalDataProcessingOversightOptions.service';
export * from './aPIV1ODATALocalDataProcessingOversightOptions.serviceInterface';
export * from './aPIV1ODATALocalDataProcessingRegistrationRoles.service';
import { APIV1ODATALocalDataProcessingRegistrationRolesService } from './aPIV1ODATALocalDataProcessingRegistrationRoles.service';
export * from './aPIV1ODATALocalDataProcessingRegistrationRoles.serviceInterface';
export * from './aPIV1ODATALocalItSystemRoles.service';
import { APIV1ODATALocalItSystemRolesService } from './aPIV1ODATALocalItSystemRoles.service';
export * from './aPIV1ODATALocalItSystemRoles.serviceInterface';
export * from './aPIV1PasswordResetRequest.service';
import { APIV1PasswordResetRequestService } from './aPIV1PasswordResetRequest.service';
export * from './aPIV1PasswordResetRequest.serviceInterface';
export * from './aPIV1Reference.service';
import { APIV1ReferenceService } from './aPIV1Reference.service';
export * from './aPIV1Reference.serviceInterface';
export * from './aPIV1SystemRelation.service';
import { APIV1SystemRelationService } from './aPIV1SystemRelation.service';
export * from './aPIV1SystemRelation.serviceInterface';
export * from './aPIV1TaskRef.service';
import { APIV1TaskRefService } from './aPIV1TaskRef.service';
export * from './aPIV1TaskRef.serviceInterface';
export * from './aPIV1Text.service';
import { APIV1TextService } from './aPIV1Text.service';
export * from './aPIV1Text.serviceInterface';
export * from './aPIV1UserAdministrationPermissions.service';
import { APIV1UserAdministrationPermissionsService } from './aPIV1UserAdministrationPermissions.service';
export * from './aPIV1UserAdministrationPermissions.serviceInterface';
export * from './aPIV1UserDeletion.service';
import { APIV1UserDeletionService } from './aPIV1UserDeletion.service';
export * from './aPIV1UserDeletion.serviceInterface';
export const APIS = [APIV1AuthorizeService, APIV1ContactpersonService, APIV1DataProcessingRegistrationService, APIV1DataProtectionAdvisorService, APIV1DataResponsibleService, APIV1DataRowService, APIV1EconomyStreamService, APIV1ExhibitService, APIV1ItContractService, APIV1ItContractItSystemUsageService, APIV1ItContractRightService, APIV1ItInterfaceService, APIV1ItSystemService, APIV1ItSystemUsageService, APIV1ItSystemUsageOrgUnitUsageService, APIV1ItSystemUsageRightsService, APIV1ODATAArchivePeriodsService, APIV1ODATAAttachedOptionsService, APIV1ODATADataProcessingRegistrationRightsService, APIV1ODATAItContractAgreementElementTypesService, APIV1ODATAItContractItSystemUsagesService, APIV1ODATAItContractRightsService, APIV1ODATAItContractsService, APIV1ODATAItInterfaceExhibitsService, APIV1ODATAItInterfacesService, APIV1ODATAItSystemRightsService, APIV1ODATAItSystemUsagesService, APIV1ODATAItSystemsService, APIV1ODATALocalDataProcessingBasisForTransferOptionsService, APIV1ODATALocalDataProcessingCountryOptionsService, APIV1ODATALocalDataProcessingDataResponsibleOptionsService, APIV1ODATALocalDataProcessingOversightOptionsService, APIV1ODATALocalDataProcessingRegistrationRolesService, APIV1ODATALocalItSystemRolesService, APIV1PasswordResetRequestService, APIV1ReferenceService, APIV1SystemRelationService, APIV1TaskRefService, APIV1TextService, APIV1UserAdministrationPermissionsService, APIV1UserDeletionService];
