/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Generic fields available for ordering
 */
export type APICommonOrderByProperty = 'CreationOrder' | 'Name' | 'LastChanged';

export const APICommonOrderByProperty = {
    CreationOrder: 'CreationOrder' as APICommonOrderByProperty,
    Name: 'Name' as APICommonOrderByProperty,
    LastChanged: 'LastChanged' as APICommonOrderByProperty
};

