/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIContractPaymentModelDataWriteRequestDTO } from './contractPaymentModelDataWriteRequestDTO';
import { APIContractAgreementPeriodDataWriteRequestDTO } from './contractAgreementPeriodDataWriteRequestDTO';
import { APIContractGeneralDataWriteRequestDTO } from './contractGeneralDataWriteRequestDTO';
import { APIContractResponsibleDataWriteRequestDTO } from './contractResponsibleDataWriteRequestDTO';
import { APIContractSupplierDataWriteRequestDTO } from './contractSupplierDataWriteRequestDTO';
import { APIContractProcurementDataWriteRequestDTO } from './contractProcurementDataWriteRequestDTO';
import { APIContractPaymentsDataWriteRequestDTO } from './contractPaymentsDataWriteRequestDTO';
import { APIContractTerminationDataWriteRequestDTO } from './contractTerminationDataWriteRequestDTO';
import { APIRoleAssignmentRequestDTO } from './roleAssignmentRequestDTO';


export interface APIContractWriteRequestDTO { 
    /**
     * UUID of the optional parent contract  Constraints:      - Parent and child contract must belong to the same organization
     */
    parentContractUuid?: string | null;
    general?: APIContractGeneralDataWriteRequestDTO;
    procurement?: APIContractProcurementDataWriteRequestDTO;
    supplier?: APIContractSupplierDataWriteRequestDTO;
    responsible?: APIContractResponsibleDataWriteRequestDTO;
    /**
     * IT-System usages covered by this it-contract  Constraints:      - System usages must belong to the same organization as the it-contract      - No duplicates
     */
    systemUsageUuids?: Array<string> | null;
    /**
     * Data processing registrations associated with this it-contract  Constraints:      - Must belong to the same organization as the it-contract      - No duplicates
     */
    dataProcessingRegistrationUuids?: Array<string> | null;
    paymentModel?: APIContractPaymentModelDataWriteRequestDTO;
    agreementPeriod?: APIContractAgreementPeriodDataWriteRequestDTO;
    termination?: APIContractTerminationDataWriteRequestDTO;
    payments?: APIContractPaymentsDataWriteRequestDTO;
    /**
     * Role assignments  Constraints:      - No duplicates
     */
    roles?: Array<APIRoleAssignmentRequestDTO> | null;
}

