/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIDataSensitivityLevelChoice = 'None' | 'PersonData' | 'SensitiveData' | 'LegalData';

export const APIDataSensitivityLevelChoice = {
    None: 'None' as APIDataSensitivityLevelChoice,
    PersonData: 'PersonData' as APIDataSensitivityLevelChoice,
    SensitiveData: 'SensitiveData' as APIDataSensitivityLevelChoice,
    LegalData: 'LegalData' as APIDataSensitivityLevelChoice
};

