/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIPublicMessageIconTypeChoice = 'Document' | 'Clipboard' | 'Settings' | 'Calendar' | 'MultipleUsers' | 'Mail';

export const APIPublicMessageIconTypeChoice = {
    Document: 'Document' as APIPublicMessageIconTypeChoice,
    Clipboard: 'Clipboard' as APIPublicMessageIconTypeChoice,
    Settings: 'Settings' as APIPublicMessageIconTypeChoice,
    Calendar: 'Calendar' as APIPublicMessageIconTypeChoice,
    MultipleUsers: 'MultipleUsers' as APIPublicMessageIconTypeChoice,
    Mail: 'Mail' as APIPublicMessageIconTypeChoice
};

