/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIYesNoIrrelevantChoice = 'No' | 'Yes' | 'Irrelevant' | 'Undecided';

export const APIYesNoIrrelevantChoice = {
    No: 'No' as APIYesNoIrrelevantChoice,
    Yes: 'Yes' as APIYesNoIrrelevantChoice,
    Irrelevant: 'Irrelevant' as APIYesNoIrrelevantChoice,
    Undecided: 'Undecided' as APIYesNoIrrelevantChoice
};

