export const ARCHIVE_B_TYPE_TEXT = $localize`Data og dokumenter bevares (B)`;
export const ARCHIVE_K_TYPE_TEXT = $localize`Data og dokumenter kasseres (K)`;
export const ARCHIVE_BK_TYPE_TEXT = $localize`Data bevares, men dokumenter kan kasseres (B+K)`;
export const ARCHIVE_KD_TYPE_TEXT = $localize`Data kasseres, og en delmængde af dokumenter kan kasseres (K+D)`;
export const ARCHIVE_KB_TYPE_TEXT = $localize`Data kasseres, men dokumenter skal bevares (K+B)`;
export const ARCHIVE_DK_TYPE_TEXT = $localize`Dele af data bevares + Dokumenter kasseres (D+K)`;
export const ARCHIVE_DD_TYPE_TEXT = $localize`Dele af data bevares + Delmængde kasseres (D+D)`;
export const ARCHIVE_PRESERVE_DATA_CAN_DISCARD_DOCUMENTS_TEXT = $localize`Data bevares, men en delmængde af dokumenter kan kasseres (B+D)`;
export const ARCHIVE_TEXT_NO_RECOMMENDATION = $localize`Ingen vejledning`;
