export const XSRFCOOKIE = 'XSRF-TOKEN';
export const XSRFTOKEN = 'X-XSRF-TOKEN';

export const DEFAULT_DATE_FORMAT = 'dd-MM-yyyy';

export const DIALOG_DEFAULT_WIDTH = 620;

export const DEFAULT_INPUT_DEBOUNCE_TIME = 300;

export const DEFAULT_NOTIFICATION_DURATION = 3500;

export const BOUNDED_PAGINATION_QUERY_MAX_SIZE = 250;
