/**
 * Naming convention {module-context}{option-type-name}
 */
export type RegularOptionType =
  | 'it-interface_interface-type'
  | 'it-system_business-type'
  | 'it-system_usage-data-classification-type'
  | 'it-system_usage-relation-frequency-type'
  | 'it_system_usage-gdpr-sensitive-data-type'
  | 'it-system_usage-archive-type'
  | 'it-system_usage-archive-location-type'
  | 'it-system_usage-archive-location-test-type'
  | 'it-contract_contract-type'
  | 'it_system_usage-gdpr-registered-data-category-type'
  | 'it-system-usage-roles'
  | 'it-interface_data-type'
  | 'it-contract_contract-template-type'
  | 'it-contract_criticality-type'
  | 'it-contract_procurement-strategy-type'
  | 'it-contract_purchase-form-type'
  | 'it-contract-agreement-element-types'
  | 'it-contract-extend-types'
  | 'it-contract-termination-period-types'
  | 'it-contract-payment-frequency-types'
  | 'it-contract-payment-model-types'
  | 'it-contract-price-regulation-types'
  | 'data-processing-data-responsible-types'
  | 'data-processing-basis-for-transfer-types'
  | 'data-processing-country-types'
  | 'data-processing-oversight-option-types';
