export * from './v2DataProcessingRegistration.service';
import { APIV2DataProcessingRegistrationService } from './v2DataProcessingRegistration.service';
export * from './v2DataProcessingRegistration.serviceInterface';
export * from './v2DataProcessingRegistrationBasisForTransferType.service';
import { APIV2DataProcessingRegistrationBasisForTransferTypeService } from './v2DataProcessingRegistrationBasisForTransferType.service';
export * from './v2DataProcessingRegistrationBasisForTransferType.serviceInterface';
export * from './v2DataProcessingRegistrationCountryType.service';
import { APIV2DataProcessingRegistrationCountryTypeService } from './v2DataProcessingRegistrationCountryType.service';
export * from './v2DataProcessingRegistrationCountryType.serviceInterface';
export * from './v2DataProcessingRegistrationDataResponsibleType.service';
import { APIV2DataProcessingRegistrationDataResponsibleTypeService } from './v2DataProcessingRegistrationDataResponsibleType.service';
export * from './v2DataProcessingRegistrationDataResponsibleType.serviceInterface';
export * from './v2DataProcessingRegistrationOversightType.service';
import { APIV2DataProcessingRegistrationOversightTypeService } from './v2DataProcessingRegistrationOversightType.service';
export * from './v2DataProcessingRegistrationOversightType.serviceInterface';
export * from './v2DataProcessingRegistrationRoleType.service';
import { APIV2DataProcessingRegistrationRoleTypeService } from './v2DataProcessingRegistrationRoleType.service';
export * from './v2DataProcessingRegistrationRoleType.serviceInterface';
export * from './v2DeltaFeed.service';
import { APIV2DeltaFeedService } from './v2DeltaFeed.service';
export * from './v2DeltaFeed.serviceInterface';
export * from './v2ItContract.service';
import { APIV2ItContractService } from './v2ItContract.service';
export * from './v2ItContract.serviceInterface';
export * from './v2ItContractAgreementElementType.service';
import { APIV2ItContractAgreementElementTypeService } from './v2ItContractAgreementElementType.service';
export * from './v2ItContractAgreementElementType.serviceInterface';
export * from './v2ItContractAgreementExtensionOptionType.service';
import { APIV2ItContractAgreementExtensionOptionTypeService } from './v2ItContractAgreementExtensionOptionType.service';
export * from './v2ItContractAgreementExtensionOptionType.serviceInterface';
export * from './v2ItContractContractTemplateType.service';
import { APIV2ItContractContractTemplateTypeService } from './v2ItContractContractTemplateType.service';
export * from './v2ItContractContractTemplateType.serviceInterface';
export * from './v2ItContractContractType.service';
import { APIV2ItContractContractTypeService } from './v2ItContractContractType.service';
export * from './v2ItContractContractType.serviceInterface';
export * from './v2ItContractCriticalityType.service';
import { APIV2ItContractCriticalityTypeService } from './v2ItContractCriticalityType.service';
export * from './v2ItContractCriticalityType.serviceInterface';
export * from './v2ItContractNoticePeriodMonthType.service';
import { APIV2ItContractNoticePeriodMonthTypeService } from './v2ItContractNoticePeriodMonthType.service';
export * from './v2ItContractNoticePeriodMonthType.serviceInterface';
export * from './v2ItContractPaymentFrequencyType.service';
import { APIV2ItContractPaymentFrequencyTypeService } from './v2ItContractPaymentFrequencyType.service';
export * from './v2ItContractPaymentFrequencyType.serviceInterface';
export * from './v2ItContractPaymentModelType.service';
import { APIV2ItContractPaymentModelTypeService } from './v2ItContractPaymentModelType.service';
export * from './v2ItContractPaymentModelType.serviceInterface';
export * from './v2ItContractPriceRegulationType.service';
import { APIV2ItContractPriceRegulationTypeService } from './v2ItContractPriceRegulationType.service';
export * from './v2ItContractPriceRegulationType.serviceInterface';
export * from './v2ItContractProcurementStrategy.service';
import { APIV2ItContractProcurementStrategyService } from './v2ItContractProcurementStrategy.service';
export * from './v2ItContractProcurementStrategy.serviceInterface';
export * from './v2ItContractPurchaseType.service';
import { APIV2ItContractPurchaseTypeService } from './v2ItContractPurchaseType.service';
export * from './v2ItContractPurchaseType.serviceInterface';
export * from './v2ItContractRoleType.service';
import { APIV2ItContractRoleTypeService } from './v2ItContractRoleType.service';
export * from './v2ItContractRoleType.serviceInterface';
export * from './v2ItInterface.service';
import { APIV2ItInterfaceService } from './v2ItInterface.service';
export * from './v2ItInterface.serviceInterface';
export * from './v2ItSystem.service';
import { APIV2ItSystemService } from './v2ItSystem.service';
export * from './v2ItSystem.serviceInterface';
export * from './v2ItSystemBusinessType.service';
import { APIV2ItSystemBusinessTypeService } from './v2ItSystemBusinessType.service';
export * from './v2ItSystemBusinessType.serviceInterface';
export * from './v2ItSystemUsage.service';
import { APIV2ItSystemUsageService } from './v2ItSystemUsage.service';
export * from './v2ItSystemUsage.serviceInterface';
export * from './v2ItSystemUsageArchiveLocationType.service';
import { APIV2ItSystemUsageArchiveLocationTypeService } from './v2ItSystemUsageArchiveLocationType.service';
export * from './v2ItSystemUsageArchiveLocationType.serviceInterface';
export * from './v2ItSystemUsageArchiveTestLocationType.service';
import { APIV2ItSystemUsageArchiveTestLocationTypeService } from './v2ItSystemUsageArchiveTestLocationType.service';
export * from './v2ItSystemUsageArchiveTestLocationType.serviceInterface';
export * from './v2ItSystemUsageArchiveType.service';
import { APIV2ItSystemUsageArchiveTypeService } from './v2ItSystemUsageArchiveType.service';
export * from './v2ItSystemUsageArchiveType.serviceInterface';
export * from './v2ItSystemUsageDataClassificationType.service';
import { APIV2ItSystemUsageDataClassificationTypeService } from './v2ItSystemUsageDataClassificationType.service';
export * from './v2ItSystemUsageDataClassificationType.serviceInterface';
export * from './v2ItSystemUsageRegisteredDataCategoryType.service';
import { APIV2ItSystemUsageRegisteredDataCategoryTypeService } from './v2ItSystemUsageRegisteredDataCategoryType.service';
export * from './v2ItSystemUsageRegisteredDataCategoryType.serviceInterface';
export * from './v2ItSystemUsageRelationFrequencyType.service';
import { APIV2ItSystemUsageRelationFrequencyTypeService } from './v2ItSystemUsageRelationFrequencyType.service';
export * from './v2ItSystemUsageRelationFrequencyType.serviceInterface';
export * from './v2ItSystemUsageRoleType.service';
import { APIV2ItSystemUsageRoleTypeService } from './v2ItSystemUsageRoleType.service';
export * from './v2ItSystemUsageRoleType.serviceInterface';
export * from './v2ItSystemUsageSensitivePersonalDataType.service';
import { APIV2ItSystemUsageSensitivePersonalDataTypeService } from './v2ItSystemUsageSensitivePersonalDataType.service';
export * from './v2ItSystemUsageSensitivePersonalDataType.serviceInterface';
export * from './v2KleOption.service';
import { APIV2KleOptionService } from './v2KleOption.service';
export * from './v2KleOption.serviceInterface';
export * from './v2Organization.service';
import { APIV2OrganizationService } from './v2Organization.service';
export * from './v2Organization.serviceInterface';
export const APIS = [APIV2DataProcessingRegistrationService, APIV2DataProcessingRegistrationBasisForTransferTypeService, APIV2DataProcessingRegistrationCountryTypeService, APIV2DataProcessingRegistrationDataResponsibleTypeService, APIV2DataProcessingRegistrationOversightTypeService, APIV2DataProcessingRegistrationRoleTypeService, APIV2DeltaFeedService, APIV2ItContractService, APIV2ItContractAgreementElementTypeService, APIV2ItContractAgreementExtensionOptionTypeService, APIV2ItContractContractTemplateTypeService, APIV2ItContractContractTypeService, APIV2ItContractCriticalityTypeService, APIV2ItContractNoticePeriodMonthTypeService, APIV2ItContractPaymentFrequencyTypeService, APIV2ItContractPaymentModelTypeService, APIV2ItContractPriceRegulationTypeService, APIV2ItContractProcurementStrategyService, APIV2ItContractPurchaseTypeService, APIV2ItContractRoleTypeService, APIV2ItInterfaceService, APIV2ItSystemService, APIV2ItSystemBusinessTypeService, APIV2ItSystemUsageService, APIV2ItSystemUsageArchiveLocationTypeService, APIV2ItSystemUsageArchiveTestLocationTypeService, APIV2ItSystemUsageArchiveTypeService, APIV2ItSystemUsageDataClassificationTypeService, APIV2ItSystemUsageRegisteredDataCategoryTypeService, APIV2ItSystemUsageRelationFrequencyTypeService, APIV2ItSystemUsageRoleTypeService, APIV2ItSystemUsageSensitivePersonalDataTypeService, APIV2KleOptionService, APIV2OrganizationService];
