export * from './v2DataProcessingRegistration.service';
import { APIV2DataProcessingRegistrationService } from './v2DataProcessingRegistration.service';
export * from './v2DataProcessingRegistrationBasisForTransferType.service';
import { APIV2DataProcessingRegistrationBasisForTransferTypeService } from './v2DataProcessingRegistrationBasisForTransferType.service';
export * from './v2DataProcessingRegistrationCountryType.service';
import { APIV2DataProcessingRegistrationCountryTypeService } from './v2DataProcessingRegistrationCountryType.service';
export * from './v2DataProcessingRegistrationDataResponsibleType.service';
import { APIV2DataProcessingRegistrationDataResponsibleTypeService } from './v2DataProcessingRegistrationDataResponsibleType.service';
export * from './v2DataProcessingRegistrationInternalINTERNAL.service';
import { APIV2DataProcessingRegistrationInternalINTERNALService } from './v2DataProcessingRegistrationInternalINTERNAL.service';
export * from './v2DataProcessingRegistrationOversightType.service';
import { APIV2DataProcessingRegistrationOversightTypeService } from './v2DataProcessingRegistrationOversightType.service';
export * from './v2DataProcessingRegistrationRoleType.service';
import { APIV2DataProcessingRegistrationRoleTypeService } from './v2DataProcessingRegistrationRoleType.service';
export * from './v2DeltaFeed.service';
import { APIV2DeltaFeedService } from './v2DeltaFeed.service';
export * from './v2GridLocalItContractRolesINTERNAL.service';
import { APIV2GridLocalItContractRolesINTERNALService } from './v2GridLocalItContractRolesINTERNAL.service';
export * from './v2ItContract.service';
import { APIV2ItContractService } from './v2ItContract.service';
export * from './v2ItContractAgreementElementType.service';
import { APIV2ItContractAgreementElementTypeService } from './v2ItContractAgreementElementType.service';
export * from './v2ItContractAgreementExtensionOptionType.service';
import { APIV2ItContractAgreementExtensionOptionTypeService } from './v2ItContractAgreementExtensionOptionType.service';
export * from './v2ItContractContractTemplateType.service';
import { APIV2ItContractContractTemplateTypeService } from './v2ItContractContractTemplateType.service';
export * from './v2ItContractContractType.service';
import { APIV2ItContractContractTypeService } from './v2ItContractContractType.service';
export * from './v2ItContractCriticalityType.service';
import { APIV2ItContractCriticalityTypeService } from './v2ItContractCriticalityType.service';
export * from './v2ItContractInternalINTERNAL.service';
import { APIV2ItContractInternalINTERNALService } from './v2ItContractInternalINTERNAL.service';
export * from './v2ItContractNoticePeriodMonthType.service';
import { APIV2ItContractNoticePeriodMonthTypeService } from './v2ItContractNoticePeriodMonthType.service';
export * from './v2ItContractPaymentFrequencyType.service';
import { APIV2ItContractPaymentFrequencyTypeService } from './v2ItContractPaymentFrequencyType.service';
export * from './v2ItContractPaymentModelType.service';
import { APIV2ItContractPaymentModelTypeService } from './v2ItContractPaymentModelType.service';
export * from './v2ItContractPriceRegulationType.service';
import { APIV2ItContractPriceRegulationTypeService } from './v2ItContractPriceRegulationType.service';
export * from './v2ItContractProcurementStrategy.service';
import { APIV2ItContractProcurementStrategyService } from './v2ItContractProcurementStrategy.service';
export * from './v2ItContractPurchaseType.service';
import { APIV2ItContractPurchaseTypeService } from './v2ItContractPurchaseType.service';
export * from './v2ItContractRoleType.service';
import { APIV2ItContractRoleTypeService } from './v2ItContractRoleType.service';
export * from './v2ItInterface.service';
import { APIV2ItInterfaceService } from './v2ItInterface.service';
export * from './v2ItInterfaceInterfaceDataType.service';
import { APIV2ItInterfaceInterfaceDataTypeService } from './v2ItInterfaceInterfaceDataType.service';
export * from './v2ItInterfaceInterfaceType.service';
import { APIV2ItInterfaceInterfaceTypeService } from './v2ItInterfaceInterfaceType.service';
export * from './v2ItSystem.service';
import { APIV2ItSystemService } from './v2ItSystem.service';
export * from './v2ItSystemBusinessType.service';
import { APIV2ItSystemBusinessTypeService } from './v2ItSystemBusinessType.service';
export * from './v2ItSystemInternalINTERNAL.service';
import { APIV2ItSystemInternalINTERNALService } from './v2ItSystemInternalINTERNAL.service';
export * from './v2ItSystemUsage.service';
import { APIV2ItSystemUsageService } from './v2ItSystemUsage.service';
export * from './v2ItSystemUsageArchiveLocationType.service';
import { APIV2ItSystemUsageArchiveLocationTypeService } from './v2ItSystemUsageArchiveLocationType.service';
export * from './v2ItSystemUsageArchiveTestLocationType.service';
import { APIV2ItSystemUsageArchiveTestLocationTypeService } from './v2ItSystemUsageArchiveTestLocationType.service';
export * from './v2ItSystemUsageArchiveType.service';
import { APIV2ItSystemUsageArchiveTypeService } from './v2ItSystemUsageArchiveType.service';
export * from './v2ItSystemUsageDataClassificationType.service';
import { APIV2ItSystemUsageDataClassificationTypeService } from './v2ItSystemUsageDataClassificationType.service';
export * from './v2ItSystemUsageInternalINTERNAL.service';
import { APIV2ItSystemUsageInternalINTERNALService } from './v2ItSystemUsageInternalINTERNAL.service';
export * from './v2ItSystemUsageMigrationINTERNAL.service';
import { APIV2ItSystemUsageMigrationINTERNALService } from './v2ItSystemUsageMigrationINTERNAL.service';
export * from './v2ItSystemUsageRegisteredDataCategoryType.service';
import { APIV2ItSystemUsageRegisteredDataCategoryTypeService } from './v2ItSystemUsageRegisteredDataCategoryType.service';
export * from './v2ItSystemUsageRelationFrequencyType.service';
import { APIV2ItSystemUsageRelationFrequencyTypeService } from './v2ItSystemUsageRelationFrequencyType.service';
export * from './v2ItSystemUsageRoleType.service';
import { APIV2ItSystemUsageRoleTypeService } from './v2ItSystemUsageRoleType.service';
export * from './v2ItSystemUsageSensitivePersonalDataType.service';
import { APIV2ItSystemUsageSensitivePersonalDataTypeService } from './v2ItSystemUsageSensitivePersonalDataType.service';
export * from './v2KleOption.service';
import { APIV2KleOptionService } from './v2KleOption.service';
export * from './v2NotificationINTERNAL.service';
import { APIV2NotificationINTERNALService } from './v2NotificationINTERNAL.service';
export * from './v2Organization.service';
import { APIV2OrganizationService } from './v2Organization.service';
export * from './v2OrganizationGridInternalINTERNAL.service';
import { APIV2OrganizationGridInternalINTERNALService } from './v2OrganizationGridInternalINTERNAL.service';
export * from './v2OrganizationUnitRegistrationInternalINTERNAL.service';
import { APIV2OrganizationUnitRegistrationInternalINTERNALService } from './v2OrganizationUnitRegistrationInternalINTERNAL.service';
export * from './v2OrganizationUnitRoleType.service';
import { APIV2OrganizationUnitRoleTypeService } from './v2OrganizationUnitRoleType.service';
export * from './v2OrganizationUnitsInternalINTERNAL.service';
import { APIV2OrganizationUnitsInternalINTERNALService } from './v2OrganizationUnitsInternalINTERNAL.service';
export * from './v2OrganizationsInternalINTERNAL.service';
import { APIV2OrganizationsInternalINTERNALService } from './v2OrganizationsInternalINTERNAL.service';
export * from './v2PublicMessagesINTERNAL.service';
import { APIV2PublicMessagesINTERNALService } from './v2PublicMessagesINTERNAL.service';
export * from './v2StsOrganizationSynchronizationInternalINTERNAL.service';
import { APIV2StsOrganizationSynchronizationInternalINTERNALService } from './v2StsOrganizationSynchronizationInternalINTERNAL.service';
export * from './v2UsersInternalINTERNAL.service';
import { APIV2UsersInternalINTERNALService } from './v2UsersInternalINTERNAL.service';
export const APIS = [APIV2DataProcessingRegistrationService, APIV2DataProcessingRegistrationBasisForTransferTypeService, APIV2DataProcessingRegistrationCountryTypeService, APIV2DataProcessingRegistrationDataResponsibleTypeService, APIV2DataProcessingRegistrationInternalINTERNALService, APIV2DataProcessingRegistrationOversightTypeService, APIV2DataProcessingRegistrationRoleTypeService, APIV2DeltaFeedService, APIV2GridLocalItContractRolesINTERNALService, APIV2ItContractService, APIV2ItContractAgreementElementTypeService, APIV2ItContractAgreementExtensionOptionTypeService, APIV2ItContractContractTemplateTypeService, APIV2ItContractContractTypeService, APIV2ItContractCriticalityTypeService, APIV2ItContractInternalINTERNALService, APIV2ItContractNoticePeriodMonthTypeService, APIV2ItContractPaymentFrequencyTypeService, APIV2ItContractPaymentModelTypeService, APIV2ItContractPriceRegulationTypeService, APIV2ItContractProcurementStrategyService, APIV2ItContractPurchaseTypeService, APIV2ItContractRoleTypeService, APIV2ItInterfaceService, APIV2ItInterfaceInterfaceDataTypeService, APIV2ItInterfaceInterfaceTypeService, APIV2ItSystemService, APIV2ItSystemBusinessTypeService, APIV2ItSystemInternalINTERNALService, APIV2ItSystemUsageService, APIV2ItSystemUsageArchiveLocationTypeService, APIV2ItSystemUsageArchiveTestLocationTypeService, APIV2ItSystemUsageArchiveTypeService, APIV2ItSystemUsageDataClassificationTypeService, APIV2ItSystemUsageInternalINTERNALService, APIV2ItSystemUsageMigrationINTERNALService, APIV2ItSystemUsageRegisteredDataCategoryTypeService, APIV2ItSystemUsageRelationFrequencyTypeService, APIV2ItSystemUsageRoleTypeService, APIV2ItSystemUsageSensitivePersonalDataTypeService, APIV2KleOptionService, APIV2NotificationINTERNALService, APIV2OrganizationService, APIV2OrganizationGridInternalINTERNALService, APIV2OrganizationUnitRegistrationInternalINTERNALService, APIV2OrganizationUnitRoleTypeService, APIV2OrganizationUnitsInternalINTERNALService, APIV2OrganizationsInternalINTERNALService, APIV2PublicMessagesINTERNALService, APIV2StsOrganizationSynchronizationInternalINTERNALService, APIV2UsersInternalINTERNALService];
