apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    easyhosting.io/service-reference: Dockerfile
    easyhosting.io/service-unique-id: 48f4e0f3-c7e4-4528-bb7f-cb8579f88fbc
    easyhosting.io/easy-hosting-domain-name: 48f4e0f3-c7e4-4528-bb7f-cb8579f88fbc.kitos-dev.strongminds.easyhosting.strongminds.dev
  labels:
    app: kitos-frontend
  name: kitos-frontend
  namespace: kitos
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: kitos-frontend
  template:
    metadata:
      annotations:
        sidecar.opentelemetry.io/inject: "false"
      labels:
        app: kitos-frontend
    spec:
      containers:
      - env:
        - name: BACKEND_URL
          value: https://kitos-dev.strongminds.dk
        image: '{will be replaced by build pipeline}'
        name: kitos-frontend
        ports:
        - containerPort: 4200
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
            cpu: 1
          requests:
            memory: 128Mi
            cpu: 100m
      imagePullSecrets:
      - name: 90d73529-a238-405b-a079-3eea2e8e36e6